homeassistant: !include configuration/homeassistant/homeassistant.yaml

# Enables support for tracking state changes over time.
history:

# enable logging
recorder:

#stay up to date with the latest homeassistant components
default_config:

# weather tracking
weather:
  - platform: buienradar
    name: 'De Bilt'

# Enables the frontend
frontend:
  themes: !include configuration/themes/themes.yaml

# Enables configuration UI
config:

#show a map
map:

google:
  client_id: 19207692763-qr70t0emisv7kn3u2862l9f39et4049j.apps.googleusercontent.com
  client_secret: !secret google_calendar

# enable lovelace
lovelace:
  mode: yaml

http:
  # Uncomment this to add a password (recommended!)
  ssl_certificate: /home/homeassistant/scripts/dehydrated/certs/de-wagnertjes.duckdns.org/fullchain.pem
  ssl_key: /home/homeassistant/scripts/dehydrated/certs/de-wagnertjes.duckdns.org/privkey.pem
  base_url: de-wagnertjes.duckdns.org

# Checks for available updates
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  include_used_components: true

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# View all events in a logbook
logbook:

# Track the sun
sun:

# Text to speech
tts:
  platform: google_translate

#enable MQTT server
mqtt:
  broker: 10.0.0.1

#notify:
#  - platform: html5
#    name: messenger
#    gcm_api_key: AAAAYtq2nrk:APA91bHuBMGc7oSo8aL23yR8g3NHt5EECi17rtZPKjJK5LeHxuwzm_l2sfDtw345ehB_P1bebvOWSTnIEb1qVtkADoftp6is1-2pN9WwB7Dg7kKJ2iAUOAbpnpeSddVxhgohcfvQ0AH7
#    gcm_sender_id: 424576196281

automation: !include_dir_merge_list configuration/automations/
binary_sensor: !include_dir_list configuration/binary_sensors/
device_tracker: !include_dir_list configuration/device_tracker/
google_assistant: !include configuration/google_assistant/google_assistant.yaml
group: !include_dir_merge_named configuration/groups/
input_select: !include configuration/input_select/resident_state.yaml
light: !include_dir_list configuration/lights/
person: !include_dir_list configuration/persons/
switch: !include_dir_list configuration/switches/
script: !include_dir_merge_named configuration/scripts/
sensor: !include_dir_merge_list configuration/sensors/
scene: !include_dir_list configuration/scenes/
utility_meter: !include configuration/utility_meter/utility_meter.yaml
zone: !include configuration/zones/zones.yaml
