title: Home

resources:
  - url: https://unpkg.com/moment@2.22.2/moment.js
    type: js
  - url: /local/custom_ui/calendar-card/calendar-card.js?v=1.0.1
    type: module
  - url: /local/atomic-calendar.js
    type: module
  - url: /local/kiosk.js?v=1.0
    type: js



views:
  - title: "Living room"
    path: living_room
    icon: mdi:floor-lamp
    cards:
      - type: vertical-stack
        cards:
        - type: entities
          entities:
          - input_select.resident_state
        - type: glance
          show_name: false
          show_state: true
          entities:
          - person.marc
          - person.koosje
          - person.roosmarijn

      - type: glance
        show_name: false
        show_state: true
        entities:
        - sensor.br_detailed_condition
        - sensor.br_temperature
        - sensor.br_humidity
        - sensor.br_wind_direction
        - sensor.br_wind_force

      - type: vertical-stack
        cards:
          - type: sensor
            name: light intensity
            graph: line
            detail: 2
            hours_to_show: 6
            entity: sensor.br_irradiance
          - type: glance
            show_state: false
            entities:
            - entity: scene.livingroom_lights
              name: lichten aan
              icon: mdi:lamp
              tap_action:
                action: call-service
                service: scene.turn_on
                service_data:
                  entity_id: scene.livingroom_lights
            - entity: scene.tv_kijken
              name: tv lichten
              icon: mdi:television
              tap_action:
                action: call-service
                service: scene.turn_on
                service_data:
                  entity_id: scene.tv_kijken
            - entity: scene.all_lights_off
              name: alles uit
              icon: mdi:weather-night
              tap_action:
                action: call-service
                service: scene.turn_on
                service_data:
                  entity_id: scene.all_lights_off

      - type: glance
        show_state: false
        entities:
        - entity: light.tv_lamp
          name: tv-lamp
          icon: mdi:lamp
          tap_action:
            action: toggle
        - entity: light.schemerlamp
          icon: mdi:lamp
          tap_action:
            action: toggle
        - entity: light.servieskast
          tap_action:
            action: toggle
        - entity: light.boekenkast_links
          tap_action:
            action: toggle
        - entity: light.boekenkast_rechts
          tap_action:
            action: toggle
        - entity: light.woonkamer_gordijn_lang
          icon: mdi:lamp
          tap_action:
            action: toggle
        - entity: light.woonkamer_gordijn_kort
          icon: mdi:lamp
          tap_action:
            action: toggle
#        - entity: light.kerstboom
#          icon: mdi:pine-tree
#          tap_action:
#            action: toggle

      - type: glance
        name: slaapkamer
        show_state: false
        entities:
        - entity: light.slaapkamer_gordijn
          name: gordijn
          tap_action:
            action: toggle
        - entity: light.slaapkamer_boekenkast
          name: boekenkast
          tap_action:
            action: toggle
        - entity: light.slaapkamer_klerenkast
          name: klerenkast
          tap_action:
            action: toggle

      - type: vertical-stack
        cards:
        - type: entities
          entities:
          - media_player.all_speakers
          - media_player.woonkamer_stereo
          - media_player.living_room_speaker
          - media_player.woonkamer
          - media_player.kitchen_speaker



  - title: ground floor
    path: groundfloor
    icon: mdi:sofa
    cards:
      - type: picture-elements
        image: /local/img/ground_floor.jpg
        elements:
          - type: state-icon
            entity: light.schemerlamp
            tap_action: 
              action: toggle
            style:
              top: 8%
              left: 8%
          - type: state-icon
            entity: light.tv_lamp
            tap_action: 
              action: toggle
            style:
              top: 8%
              left: 45%
          - type: state-icon
            entity: light.servieskast
            tap_action: 
              action: toggle
            style:
              top: 63%
              left: 7%
          - type: state-icon
            entity: light.boekenkast_links
            tap_action: 
              action: toggle
            style:
              top: 95%
              left: 36%
          - type: state-icon
            entity: light.boekenkast_rechts
            tap_action: 
              action: toggle
            style:
              top: 95%
              left: 44%
          - type: state-icon
            entity: light.woonkamer_gordijn_kort
            tap_action: 
              action: toggle
            style:
              top: 95%
              left: 18%
          - type: state-icon
            entity: light.woonkamer_gordijn_lang
            tap_action: 
              action: toggle
            style:
              top: 68%
              left: 45%
          - type: state-label
            entity: sensor.hall_temperature
            style:
              top: 38%
              left: 60%
          - type: state-label
            entity: sensor.hall_humidity
            style:
              top: 42%
              left: 60%
          - type: state-icon
            entity: binary_sensor.hall_motion
            style:
              top: 30%
              left: 52%
          - type: state-icon
            entity: switch.hall_mirror
            tap_action: 
              action: toggle
            style:
              top: 30%
              left: 59%

      - type: media-control
        entity: media_player.all_speakers
      - type: media-control
        entity: media_player.kitchen_speaker
      - type: media-control
        entity: media_player.living_room_speaker
      - type: media-control
        entity: media_player.woonkamer
      - type: media-control
        entity: media_player.woonkamer_stereo





  - title: first floor
    path: firstfloor
    icon: mdi:bed-empty
    cards:
      - type: picture-elements
        image: /local/img/1st_floor.jpg
        elements:
          - type: state-icon
            entity: light.slaapkamer_klerenkast
            tap_action: 
              action: toggle
            style:
              top: 35%
              left: 15%
          - type: state-icon
            entity: light.slaapkamer_boekenkast
            tap_action: 
              action: toggle
            style:
              top: 15%
              left: 23%
          - type: state-icon
            entity: light.slaapkamer_boekenkast
            tap_action: 
              action: toggle
            style:
              top: 65%
              left: 8%
          - type: state-icon
            entity: light.slaapkamer_gordijn
            tap_action: 
              action: toggle
            style:
              top: 70%
              left: 29%
          - type: state-label
            entity: sensor.slaapkamer_temperature
            style:
              top: 80%
              left: 28%
      - type: entities
        entities:
          - script.slaapkamer_gordijn_fade_in
          - script.slaapkamer_boekenkast_fade_in


  - title: 2nd floor
    path: secondfloor
    icon: mdi:hotel
    cards:
      - type: picture-elements
        image: /local/img/2nd_floor.jpg




  - title: hall
    path: hall
    icon: mdi:door-open
    theme: Dark
    panel: true
    cards:
      - type: horizontal-stack
        cards:
           - type: vertical-stack
             cards:
               - type: iframe
                 url: /local/clock.html
                 aspect_ratio: 110%
               - type: "custom:atomic-calendar"
                 maxDaysToShow: 8
                 entities:
                   - calendar.holidays_in_netherlands
                   - calendar.contacts
                   - calendar.koosjeenmarcgmailcom
                   - calendar.koosje_wagner
                   - calendar.koosje_werk
                   - calendar.marc_wagner
                   - calendar.koosje_maar_wel_relevant_voor_marc
                   - calendar.prive_woonboot

           - type: vertical-stack
             cards:
#               - type: map
#                aspect_ratio: 4:3
#                 default_zoom: 16
#                 entities:
#                   - zone.home
#                   - device_tracker.phoneroosmarijn
#                   - device_tracker.phonekoosje
#                   - device_tracker.phonemarc

               - type: glance
                 show_name: false
                 show_state: true
                 entities:
                   - person.marc
                   - person.koosje
                   - person.roosmarijn


           - type: vertical-stack
             cards:
             - type: weather-forecast
               entity: weather.de_bilt

             - type: horizontal-stack
               cards:
               - type: sensor
                 entity: sensor.hall_temperature
                 unit: 'C'
                 name: temperature

               - type: sensor
                 entity: sensor.hall_humidity
                 unit: '%'
                 name: humidity

             - type: horizontal-stack
               cards:
                 - type: sensor
                   title: Energie
                   name: stroom
                   entity: sensor.power_use
                   graph: line
                   detail: 2
                   unit: Watt/s
                   icon: mdi:flash

                 - type: sensor
                   title: Gas
                   name: gas
                   entity: sensor.gas_use
                   graph: line
                   detail: 2
                   unit: mL/s
                   icon: mdi:fire
