 
title: Home

resources:
  - url: /local/custom-lovelace/kiosk.js?v=0.0.1
    type: js
  - url: https://unpkg.com/moment@2.22.2/moment.js
    type: js
  - url: /local/custom-lovelace/calendar-card.js?v=1.0.1
    type: module
  - url: /local/custom-lovelace/atomic-calendar.js
    type: module
  - url: /local/custom-lovelace/custom-header.js?v=0.0.1
    type: module

custom_header:
  header_text: Wagner - Home Assistant
  exceptions:
    - conditions:
        user: kiosk
      config:
        kiosk_mode: true

views:
  - !include configuration/lovelace/main_view.yaml
  - !include configuration/lovelace/ground_floor.yaml
  - !include configuration/lovelace/first_floor.yaml
  - !include configuration/lovelace/hall.yaml
