- platform: mqtt
  name: "boekenkast_motion"
  state_topic: "boekenkast/stat/SWITCH1"
  value_template: "{{ value_json.STATE }}"
  availability_topic: "boekenkast/tele/LWT"
  payload_available: "Online"
  payload_not_available: "Offline"
  device_class: motion
  qos: 1


- platform: mqtt
  name: "werkplek_motion"
  state_topic: "werkplek/stat/SWITCH1"
  value_template: "{{ value_json.STATE }}"
  availability_topic: "boekenkast/tele/LWT"
  payload_available: "Online"
  payload_not_available: "Offline"
  device_class: motion
  qos: 1
